--
-- Base de Dados: `prova`
--

DROP DATABASE IF EXISTS `prova`;
CREATE DATABASE IF NOT EXISTS `prova` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `prova`;

-- --------------------------------------------------------

--
-- Estrutura da tabela `opcao`
--

DROP TABLE IF EXISTS `opcao`;
CREATE TABLE IF NOT EXISTS `opcao` (
	`id` int(11) NOT NULL AUTO_INCREMENT,
	`pergunta_id` int(11) NOT NULL,
	`titulo` text NOT NULL,
	`correta` int(1) NOT NULL,
	PRIMARY KEY (`id`),
	KEY `pergunta_id` (`pergunta_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Extraindo dados da tabela `opcao`
--

INSERT INTO `opcao` (`id`, `pergunta_id`, `titulo`, `correta`) VALUES
(1, 1, 'regulamentar as manobras, luzes de navegação e de condições especiais, em águas de jurisdição nacional', 0),
(2, 1, 'evitar o abalroamento no mar, utilizando-se regras internacionais de navegação, luzes e marcas e ainda sinais sonoros', 1),
(3, 1, 'evitar o abalroamento em águas nacionais através de regras de governo e navegação, luzes, marcas e sinais sonoros', 0),
(4, 1, 'evitar a colisão em mar aberto, em águas internacionais, através de regras de governo, luzes, marcas e sinais sonoros', 0),
(5, 2, 'proa com proa, as duas guinam para boreste', 1),
(6, 2, 'rumos cruzados, as duas guinam para boreste', 0),
(7, 2, 'rumos cruzados, as duas guinam para os bordos opostos', 0),
(8, 2, 'proa com proa, as duas guinam para os bordos opostos', 0),
(9, 3, 'nenhuma delas, as duas guinam para os bordos opostos', 0),
(10, 3, 'a que está com maior velocidade', 0),
(11, 3, 'a que tem maior tonelagem, ou seja, maior porte (tamanho)', 0),
(12, 3, 'a que avistar a outra por seu bombordo, isto é, a que vê a luz verde', 1),
(13, 4, 'não, a que está com menor velocidade, a frente da outra, deverá manobrar para dar passagem a que está alcançando', 0),
(14, 4, 'sim, a que está com menor velocidade, a frente da outra, deverá manobrar para dar passagem a que está alcançando', 0),
(15, 4, 'não, a que está com maior velocidade, alcançadora, deverá manobrar para passar pela outra, à frente', 1),
(16, 4, 'sim, a que está com maior velocidade, alcançadora, deverá manobrar para passar pela outra, à frente', 0),
(17, 5, 'o veleiro estava certo e portanto não teve culpa nenhuma no acidente, cabendo total responsabilidade à lancha', 0),
(18, 5, 'a lancha estava errada e portanto deveria ter manobrado com antecedência, porém o veleiro deve se manter longe de outras embarcações a motor, o que dificultou a análise da culpa', 0),
(19, 5, 'as duas deveriam ter guinado para os bordos opostos conforme manda a regra, no caso previsto, independentemente da preferência de passagem em função do tipo de operação ou de embarcação', 0),
(20, 5, 'apesar da lancha ter errado por não manobrar, para evitar o acidente, o veleiro não pode ser isentado de culpa pois, a embarcação que tem preferência deverá manobrar para evitar a colisão, caso a outra, obrigada a manobrar, não o faça.', 1),
(21, 6, 'franca e positiva, feita com ampla antecedência, demonstrando à outra embarcação, que houve alteração de movimento ', 1),
(22, 6, 'gradual e com pouca alteração de velocidade, para se evitar confusão no acompanhamento da outra embarcação', 0),
(23, 6, 'brusca e com variações constantes de velocidade, para que a outra embarcação perceba a alteração do rumo', 0),
(24, 6, 'lenta e com pequenos ângulos de leme, para que não haja confusão na interpretação dos movimentos pela outra embarcação', 0),
(25, 7, 'a que vem a favor da corrente deverá se posicionar no meio do rio e a outra na sua margem direita, sendo que a que vem a favor da corrente tem preferência', 0),
(26, 7, 'a que vem contra a corrente deverá se posicionar no meio do rio e a outra na sua margem direita, sendo que a que vem contra a corrente tem preferência', 0),
(27, 7, 'a que vem a favor da corrente deverá se posicionar no meio do rio e a outra na sua margem de boreste, sendo que a que vem a favor da corrente tem preferência', 1),
(28, 7, 'a que vem contra a corrente deverá se posicionar na margem de bombordo mais próxima, e a outra no meio do rio, não havendo preferência de manobra entre elas', 0),
(29, 8, 'navegar pela margem mais próxima a seu bombordo e sempre manobrar para boreste quando verificar o risco de colisão', 0),
(30, 8, 'navegar pela margem mais próxima a seu boreste e sempre manobrar para boreste quando verificar o risco de colisão', 1),
(31, 8, 'navegar pela margem mais próxima a seu bombordo e sempre manobra para bombordo quando verificar o risco de colisão', 0),
(32, 8, 'navegar pela margem mais próxima a seu boreste e sempre manobrar para bombordo quando verificar o risco de colisão', 0),
(33, 9, 'preferência', 1),
(34, 9, 'que manobrar', 0),
(35, 9, 'deixar o seu boreste livre para a outra', 0),
(36, 9, 'manter o seu rumo e velocidade independente da situação da outra', 0),
(37, 10, 'é a velocidade máxima permitida em uma determinada região de tráfego; devemos manter a velocidade para evitar variações da corrente de esteira da embarcação', 0),
(38, 10, 'é a velocidade mínima para se parar a embarcação com segurança; devemos diminuir a velocidade', 0),
(39, 10, 'é a velocidade que possibilita uma ação apropriada e eficaz de evitar uma colisão e de parar a embarcação a uma distância segura; devemos diminuir a velocidade', 1),
(40, 10, 'é a velocidade ideal de cruzeiro da embarcação para condições que exijam maiores cuidados na navegação com baixa visibilidade; devemos diminuir a velocidade', 0),
(41, 11, 'uma embarcação engajada na pesca', 0),
(42, 11, 'uma embarcação a motor', 1),
(43, 11, 'uma embarcação com capacidade de manobra restrita', 0),
(44, 11, 'uma embarcação sem governo', 0),
(45, 12, 'uma luz branca no mastro a vante, uma luz branca no mastro a ré, mais alta do que a de vante, uma luz de alcançado à ré, branca, luzes, verde a boreste e encarnada (vermelha) a bombordo', 0),
(46, 12, 'uma luz branca a vante, uma luz branca a ré, luzes, verde a boreste e encarnada (vermelha) a bombordo', 0),
(47, 12, 'uma luz branca a vante, uma luz de alcançado branca, luzes verde e encarnada (vermelha), combinadas', 1),
(48, 12, 'uma luz branca a vante, uma luz branca a ré, uma luz de alcançado branca, luzes verde e encarnada(vermelha), combinadas', 0),
(49, 13, 'manobra, advertência e risco de colisão', 0),
(50, 13, 'manobra, risco de colisão e em canais estreitos', 0),
(51, 13, 'manobra, advertência e em baixa visibilidade', 1),
(52, 13, 'manobra, risco de colisão e em baixa visibilidade', 0),
(53, 14, 'estou dando atrás', 0),
(54, 14, 'estou guinando para boreste', 1),
(55, 14, 'estou guinando para bombordo', 0),
(56, 14, 'estou parando máquinas', 0),
(57, 15, 'estou dando atrás', 0),
(58, 15, 'estou guinando para boreste', 0),
(59, 15, 'estou guinando para bombordo', 1),
(60, 15, 'estou parando máquinas', 0),
(61, 16, 'estou dando atrás', 1),
(62, 16, 'estou guinando para boreste', 0),
(63, 16, 'estou guinando para bombordo', 0),
(64, 16, 'estou parando máquinas', 0),
(65, 17, 'estou dando atrás', 0),
(66, 17, 'estou ultrapassando por boreste', 0),
(67, 17, 'estou ultrapassando por bombordo', 1),
(68, 17, 'estou parando máquinas', 0),
(69, 18, 'em canais de tráfego intenso, para evitar colisão, à noite', 0),
(70, 18, 'em rios estreitos para, à noite, iluminar curvas', 1),
(71, 18, 'para sinalizar que a embarcação encontra-se em perigo', 0),
(72, 18, 'para se navegar no porto quando estiver com visibilidade restrita', 0),
(73, 19, 'estou dando atrás', 0),
(74, 19, 'estou parando máquinas', 0),
(75, 19, 'embarcação fundeada em visibilidade restrita', 0),
(76, 19, 'não entendi suas intenções de manobra', 1),
(77, 20, 'embarcação a motor em movimento, com visibilidade restrita', 1),
(78, 20, 'embarcação fundeada, em visibilidade restrita', 0),
(79, 20, 'embarcação parada, em visibilidade restrita', 0),
(80, 20, 'embarcação rebocando outra', 0),
(81, 21, 'embarcação a motor em movimento, com visibilidade restrita', 0),
(82, 21, 'embarcação fundeada, em visibilidade restrita', 0),
(83, 21, 'embarcação parada, em visibilidade restrita', 1),
(84, 21, 'embarcação rebocando', 0),
(85, 22, 'uma embarcação à vela', 0),
(86, 22, 'uma embarcação com capacidade de manobra restrita', 0),
(87, 22, 'uma embarcação engajada na pesca', 0),
(88, 22, 'todas as embarcações citadas', 1),
(89, 23, 'uma embarcação a motor', 1),
(90, 23, 'uma embarcação com capacidade de manobra restrita', 0),
(91, 23, 'uma embarcação engajada na pesca', 0),
(92, 23, 'uma embarcação sem governo', 0),
(93, 24, 'fundeada', 1),
(94, 24, 'sem governo', 0),
(95, 24, 'com carga perigosa', 0),
(96, 24, 'navegando', 0),
(97, 25, 'uma luz branca no mastro', 0),
(98, 25, 'duas luzes brancas no mastro', 1),
(99, 25, 'três luzes brancas no mastro', 0),
(100, 25, 'quatro luzes brancas no mastro', 0),
(101, 26, 'uma luz branca no mastro', 0),
(102, 26, 'duas luzes brancas no mastro', 0),
(103, 26, 'três luzes brancas no mastro', 1),
(104, 26, 'quatro luzes brancas no mastro', 0),
(105, 27, 'ela está fundeada', 0),
(106, 27, 'ela está sem governo', 0),
(107, 27, 'ela carrega cargas perigosas', 1),
(108, 27, 'ela tem preferência pois está com capacidade de manobra restrita', 0),
(109, 28, 'engajada em pesca de arrasto', 0),
(110, 28, 'sem governo', 0),
(111, 28, 'pairando sob máquinas', 0),
(112, 28, 'fundeada', 1),
(113, 29, 'um apito longo para chamar atenção', 1),
(114, 29, 'dois apitos curtos para chamar atenção', 0),
(115, 29, 'um apito longo seguido de um apito curto para indicar que eu vou fazer a curva', 0),
(116, 29, 'dois apitos longos para indicar que eu vou fazer a curva', 0),
(117, 30, '2 segundos', 0),
(118, 30, '4 a 6 segundos', 0),
(119, 30, '1 minuto', 0),
(120, 30, 'aproximadamente 1 segundo', 1),
(121, 31, '2 segundos', 0),
(122, 31, '4 a 6 segundos', 1),
(123, 31, '1 minuto', 0),
(124, 31, 'aproximadamente 1 segundo', 0),
(125, 32, 'boreste com boreste', 0),
(126, 32, 'boreste com bombordo', 0),
(127, 32, 'bombordo com bombordo', 1),
(128, 32, 'cortando a sua proa', 0),
(129, 33, 'à noite', 0),
(130, 33, 'com embarcação atracada no cais', 1),
(131, 33, 'em visibilidade restrita', 0),
(132, 33, 'quando for necessário', 0),
(133, 34, 'buzina ou sino para sinalizar suas intenções', 1),
(134, 34, 'um gongo para manobrar à noite', 0),
(135, 34, 'um holofote durante o tráfego em canal balizado', 0),
(136, 34, 'uma série de foguetes pirotécnicos lançados seqüencialmente', 0),
(137, 35, 'dispensadas de usar buzina ou outro dispositivo que a substitua', 1),
(138, 35, 'obrigadas a ter pelo menos as luzes de bordo', 0),
(139, 35, 'dispensadas de exibir luzes à noite', 0),
(140, 35, 'obrigadas a exibir uma luz branca circular à noite', 0),
(141, 36, 'um toque contínuo de qualquer aparelho de sinalização de cerração', 0),
(142, 36, 'um sinal de fumaça de cor alaranjada', 0),
(143, 36, 'foguetes lançando estrelas encarnadas', 0),
(144, 36, 'um balão preto içado no mastro principal onde melhor possa ser visto', 1),
(145, 37, 'a lancha da Capitania dos Portos fazendo polícia naval', 0),
(146, 37, 'uma embarcação desenvolvendo uma grande velocidade ao navegar', 1),
(147, 37, 'uma embarcação dos serviços de praticagem do porto', 0),
(148, 37, 'um rebocador do porto se dirigindo para a manobra', 0),
(149, 38, 'sempre com a proa voltada para a sinalização de boreste', 0),
(150, 38, 'sempre em baixa velocidade e apitando', 0),
(151, 38, 'de forma a cruzar perpendicularmente a via de tráfego', 1),
(152, 38, 'sempre fazendo alterações constantes de direção', 0),
(153, 39, 'circulares', 0),
(154, 39, 'circulares brancas', 0),
(155, 39, 'de acordo com o tipo de embarcação', 0),
(156, 39, 'setorizadas para melhor identificar o movimento da embarcação, à noite ', 1),
(157, 40, 'estou dando atrás', 0),
(158, 40, 'estou ultrapassando por boreste', 1),
(159, 40, 'estou ultrapassando por bombordo', 0),
(160, 40, 'estou parando máquinas', 0),
(161, 41, 'tipo de leme', 0),
(162, 41, 'condições do vento', 0),
(163, 41, 'temperatura da água', 1),
(164, 41, 'número de propulsores', 0),
(165, 42, 'estrutura metálica ou de madeira, que tem por finalidade dar direção a embarcação e mantê-la no rumo determinado', 1),
(166, 42, 'estrutura localizada na popa da embarcação, que serve para guiná-la com a ação dos motores', 0),
(167, 42, 'estrutura metálica ou de madeira, que possui cana do leme e serve para impulsionar a embarcação, numa direção determinada', 0),
(168, 42, 'estrutura geralmente de ferro, que possui alhetas que direcionam a embarcação, num rumo determinado', 0),
(169, 43, 'estrutura metálica, que possui pás e serve para movimentar a embarcação através de seu próprio giro, acoplado através de um eixo longitudinal a um motor', 1),
(170, 43, 'estrutura metálica, que possui pás e serve para impulsionar a embarcação, através de seu eixo longitudinal', 0),
(171, 43, 'estrutura metálica, que possui pás laterais, que formam uma cavitação longitudinal, que impulsiona o leme para movimentar a embarcação', 0),
(172, 43, 'estrutura metálica, capaz de girar no seu eixo, e movimentar a embarcação no sentido dos bordos, para atracá-la e desatracá-la', 0),
(173, 44, 'prender no fundo, para permitir que a embarcação garre', 0),
(174, 44, 'fundear nos fundeadouros de boa tença', 0),
(175, 44, 'prender no fundo, para permitir que a embarcação se mantenha fundeada, ou seja, sem se deslocar da posição', 1),
(176, 44, 'fundear nos fundeadouros com vento forte ou correnteza, para evitar que a embarcação garre', 0),
(177, 45, 'elos que servem para prender a âncora ao anete', 0),
(178, 45, 'elos ou cabos que servem para prender a âncora ao porão da amarra', 0),
(179, 45, 'elos ou cabos que servem para prender a âncora ao paiol da amarra ou ao convés da embarcação', 1),
(180, 45, 'elos ou cabos que servem para prender a âncora ao escovém da embarcação', 0),
(181, 46, 'as condições de vento, correntes e maré, procurando afilar-se ao que predominar mais', 1),
(182, 46, 'as condições de vento e corrente, procurando dar máquina atrás antes de largar a âncora e parando, após ter prendido no fundo', 0),
(183, 46, 'as condições de mar, sempre verificando o tipo de tença e a profundidade local, para saber quantas âncoras largar', 0),
(184, 46, 'as condições de tempo, para verificar o local de fundeio', 0),
(185, 47, 'ser abrigado de ventos, correntes e ondas', 0),
(186, 47, 'ter uma profundidade adequada ao fundeio', 0),
(187, 47, 'ter um fundo de boa tença', 0),
(188, 47, 'ter um espaço limitado para não se fundear fora da área permitida', 1),
(189, 48, 'aproximar-se do cais, num ângulo de 90º, de modo a passar um cabo de proa logo que possa, colocando o leme para o bordo do cais, para deslocar a popa para este', 0),
(190, 48, 'aproximar-se do cais, num ângulo de 45º, de modo a passar um cabo de proa logo que possa, colocando o leme para o bordo oposto do cais, para deslocar a popa para este', 1),
(191, 48, 'aproximar-se do cais, num ângulo de 90º, de modo a passar um cabo de proa logo que possa, colocando o leme para o bordo oposto ao do cais, para deslocar a popa para este', 0),
(192, 48, 'aproximar-se do cais, com qualquer ângulo, desde que, sem seguimento, guinando-se a popa para o cais e passando o cabo de ré', 0),
(193, 49, 'lançantes, espringues e traveses', 1),
(194, 49, 'lançantes de proa e de popa e traveses', 0),
(195, 49, 'espringues de proa e de popa e retinidas', 0),
(196, 49, 'lançantes, espringues e retinidas', 0),
(197, 50, 'são cabos de amarração usados na faina de atracar uma embarcação', 1),
(198, 50, 'são cabos de fibra vegetal ou sintética, que servem para prender a embarcação a uma bóia ou a outra embarcação', 0),
(199, 50, 'são retinidas, que servem para conduzir os cabos de amarração', 0),
(200, 50, 'são cabos de aço ou ferro, que servem para prender as amarras às âncoras, em embarcão de esporte e recreio', 0),
(201, 51, 'atracar a favor da corrente, para aproveitar seu efeito de encostar a embarcação ao cais', 0),
(202, 51, 'atracar com um cabo dizendo para vante e outro dizendo para ré', 0),
(203, 51, 'atracar contra a corrente, passando-se um cabo dizendo para vante e outro dizendo para ré', 1),
(204, 51, 'esperar a corrente cessar, para evitar seu efeito, que é prejudicial a manobra de atracação', 0),
(205, 52, 'largar os cabos de vante e abrir a proa dando máquina adiante, para folgar os cabos de ré', 0),
(206, 52, 'largar os cabos de ré, procurando manobrar para abrir a popa e com, o motor dando atrás, aproveitar o efeito do leme para afastar a popa e então largar os cabos de vante', 1),
(207, 52, 'largar os cabos de ré, procurando utilizar os cabos de vante para abrir a popa com máquina adiante toda a força', 0),
(208, 52, 'largar todos os cabos e dar máquina adiante toda a força, para sair rapidamente do cais', 0),
(209, 53, 'folgando primeiro os cabos de vante e mantendo os de ré apertados', 1),
(210, 53, 'folgando primeiro os cabos de ré e mantendo os de vante apertados', 0),
(211, 53, 'folgando todos os cabos e largando a embarcação ao efeito da corrente', 0),
(212, 53, 'espera-se o efeito da corrente cessar, para iniciar a manobra de desatracação', 0),
(213, 54, 'para amarrar a embarcação num local próximo à marina', 0),
(214, 54, 'para evitar que a embarcação garre', 0),
(215, 54, 'para indicar o local onde a âncora ficou presa no fundo', 1),
(216, 54, 'para determinar o local onde podemos fundear com segurança', 0),
(217, 55, 'proa, popa, boca, quilha, bordos e convés', 1),
(218, 55, 'través, calado e borda livre', 0),
(219, 55, 'a vante, a ré e meia-nau', 0),
(220, 55, 'boreste, bombordo e trim', 0),
(221, 56, 'lançante de proa', 0),
(222, 56, 'espringue de popa', 0),
(223, 56, 'través', 1),
(224, 56, 'retinida', 0),
(225, 57, 'bombordo', 0),
(226, 57, 'boreste rapidamente', 0),
(227, 57, 'boreste lentamente', 1),
(228, 57, 'bombordo lentamente', 0),
(229, 58, 'bombordo', 0),
(230, 58, 'boreste rapidamente', 0),
(231, 58, 'boreste lentamente', 1),
(232, 58, 'bombordo rapidamente', 0),
(233, 59, 'bombordo rapidamente', 0),
(234, 59, 'boreste rapidamente', 0),
(235, 59, 'bombordo lentamente', 0),
(236, 59, 'boreste', 1),
(237, 60, 'bombordo', 0),
(238, 60, 'boreste lentamente', 1),
(239, 60, 'boreste rapidamente', 0),
(240, 60, 'bombordo lentamente', 0),
(241, 61, 'bombordo', 1),
(242, 61, 'boreste ', 0),
(243, 61, 'bombordo lentamente', 0),
(244, 61, 'boreste rapidamente', 0),
(245, 62, 'bombordo', 0),
(246, 62, 'boreste ', 0),
(247, 62, 'boreste rapidamente', 1),
(248, 62, 'bombordo lentamente', 0),
(249, 63, 'bombordo lentamente', 1),
(250, 63, 'boreste rapidamente', 0),
(251, 63, 'boreste muito lentamente', 0),
(252, 63, 'boreste lentamente', 0),
(253, 64, 'bombordo lentamente', 0),
(254, 64, 'boreste rapidamente', 0),
(255, 64, 'boreste muito lentamente', 0),
(256, 64, 'boreste lentamente', 1),
(257, 65, 'bombordo lentamente', 0),
(258, 65, 'boreste rapidamente', 0),
(259, 65, 'boreste muito lentamente', 0),
(260, 65, 'boreste lentamente', 1),
(261, 66, 'bombordo lentamente', 0),
(262, 66, 'boreste rapidamente', 0),
(263, 66, 'boreste muito lentamente', 0),
(264, 66, 'boreste lentamente', 1),
(265, 67, 'bombordo rapidamente', 1),
(266, 67, 'boreste rapidamente', 0),
(267, 67, 'boreste muito lentamente', 0),
(268, 67, 'boreste lentamente', 0),
(269, 68, 'bombordo', 0),
(270, 68, 'boreste muito lentamente', 1),
(271, 68, 'boreste rapidamente', 0),
(272, 68, 'bombordo rapidamente', 0),
(273, 69, 'sair com a embarcação do local de fundeio, recolhendo a âncora', 1),
(274, 69, 'levantar um peso a bordo', 0),
(275, 69, 'sair com a embarcação do cais', 0),
(276, 69, 'desamarrar a embarcação de uma bóia', 0),
(277, 70, 'fateixa', 0),
(278, 70, 'busca-vida', 0),
(279, 70, 'danforth', 1),
(280, 70, 'almirantado', 0),
(281, 71, 'madre, cana e porta', 1),
(282, 71, 'cabeça corpo e dobradiças', 0),
(283, 71, 'corpo, anete e cepo', 0),
(284, 71, 'cabeça, anete e haste', 0),
(285, 72, 'paralela ao cais, com muito seguimento', 0),
(286, 72, 'paralela ao cais, com pouco seguimento', 1),
(287, 72, 'com ângulo de 90º com o cais', 0),
(288, 72, 'com muito seguimento e pouca inclinação ao cais', 0),
(289, 73, 'paralela ao cais, com muito seguimento', 0),
(290, 73, 'paralela ao cais, com pouco seguimento', 0),
(291, 73, 'com um ângulo aproximado de 45º com o cais', 1),
(292, 73, 'com um ângulo de 90º com o cais', 0),
(293, 74, 'a favor do que predominar e paralelo ao cais', 0),
(294, 74, 'sempre contrário ao vento ou corrente, com ângulo agudo ao cais', 1),
(295, 74, 'com ângulo agudo ao cais e pouco seguimento', 0),
(296, 74, 'a favor da corrente ou vento e com pouco seguimento', 0),
(297, 75, 'largar todas as espias do cais e dar máquina adiante devagar', 0),
(298, 75, 'com leme contrário ao cais e máquina devagar adiante, largar todas as espias, exceto a de ré, que esteja dizendo para vante', 1),
(299, 75, 'com o leme a meio e máquina devagar a ré, largar todas as espias exceto a de vante', 0),
(300, 75, 'largar todas as espias e dar atrás com a máquina, com leme a meio', 0),
(301, 76, 'largar todas as espias, exceto a que diz para vante, na popa, mantendo o leme contrário ao cais', 1),
(302, 76, 'largar todas as espias e manter o leme a meio', 0),
(303, 76, 'largar todas as espias, exceto a que diz para vante, na proa, mantendo o leme a meio', 0),
(304, 76, 'largar todas as espias, exceto a que diz para ré, na popa, mantendo o leme contrário ao cais', 0),
(305, 77, 'largar todas as espias, exceto a que diz para vante, na popa, mantendo o leme contrário ao cais', 0),
(306, 77, 'largar todas as espias e manter o leme a meio', 1),
(307, 77, 'largar todas as espias, exceto a que diz para ré, na proa, mantendo o leme na direção do cais', 0),
(308, 77, 'largar todas as espias, exceto a que diz para vante, na proa, mantendo o leme na direção do cais', 0),
(309, 78, 'lama', 0),
(310, 78, 'lodo mole', 0),
(311, 78, 'areia mole', 0),
(312, 78, 'areia dura', 1),
(313, 79, 'no mínimo 2 vezes a profundidade local', 0),
(314, 79, 'no mínimo 1,5 vezes a profundidade local', 0),
(315, 79, 'no mínimo 3 vezes a profundidade local', 1),
(316, 79, 'no mínimo 6 vezes a profundidade local', 0),
(317, 80, '8 vezes a profundidade local', 0),
(318, 80, '5 vezes a profundidade local', 1),
(319, 80, '6 vezes a profundidade local', 0),
(320, 80, 'no mínimo 8 vezes a profundidade local', 0),
(321, 81, 'aproados a ela, com pouco seguimento', 1),
(322, 81, 'paralelos a ela, com muito seguimento', 0),
(323, 81, 'dando atrás, ao passarmos da bóia', 0),
(324, 81, 'aproados a ela, com muito seguimento', 0),
(325, 82, 'tipo de material que fica no fundo, para segurar a embarcação', 0),
(326, 82, 'tipo de fundo (qualidade)', 1),
(327, 82, 'tipo de âncora', 0),
(328, 82, 'ondulações que geram perfis diferenciados do fundo', 0),
(329, 83, 'com pouca profundidade', 0),
(330, 83, 'com fundo de lama', 0),
(331, 83, 'com possibilidades de ventos e correntes', 0),
(332, 83, 'onde o espaço de giro da embarcação seja limitado', 1),
(333, 84, 'ir recolhendo âncora, com máquina devagar adiante, caso a amarra esteja tesada para vante', 1),
(334, 84, 'ir recolhendo a âncora, com máquina devagar atrás', 0),
(335, 84, 'ir recolhendo a âncora, observando a posição da amarra em relação a proa da embarcação', 0),
(336, 84, 'ir recolhendo a âncora, com máquina devagar adiante, caso a amarra esteja perpendicular a embarcação', 0),
(337, 85, 'marcação variando e distância aumentando', 0),
(338, 85, 'marcação variando e distância diminuindo', 0),
(339, 85, 'marcação constante e distância diminuindo', 1),
(340, 85, 'marcação constante e distância aumentando', 0),
(341, 86, 'para a máquina e largar a âncora', 0),
(342, 86, 'inverter a máquina e quando estiver caindo à ré, largar a âncora', 1),
(343, 86, 'largar a âncora com seguimento a vante', 0),
(344, 86, 'quando a embarcação estiver sem seguimento, largar a âncora e dar máquina devagar adiante', 0),
(345, 87, 'tende a seguir em linha reta para vante', 0),
(346, 87, 'tende a girar a proa para o mesmo bordo do hélice que dá atrás', 1),
(347, 87, 'tende a girar a proa para o bordo contrário ao do hélice que dá atrás', 0),
(348, 87, 'tende a girar a proa para o mesmo bordo do hélice que dá adiante', 0),
(349, 88, 'sempre aproar ao que tiver mais forte', 0),
(350, 88, 'aproar ao vento, caso a embarcação tiver uma estrutura alta no convés', 1),
(351, 88, 'aproar à corrente, independente do vento', 0),
(352, 88, 'fundear, independente do efeito do vento ou da corrente', 0),
(353, 89, 'a embarcação que navega subindo o canal deve manobrar para boreste e a outra manter o rumo', 0),
(354, 89, 'a embarcação que navega descendo o canal deve manobrar para boreste e a outra manter o rumo', 0),
(355, 89, 'ambas devem tomar a margem de seu boreste', 1),
(356, 89, 'ambas devem manter-se boreste com boreste', 0),
(357, 90, 'boreste - lado direito da embarcação, bombordo - lado esquerdo da embarcação, a avante - fica na frente, a ré - fica atrás', 1),
(358, 90, 'boreste - lado esquerdo da embarcação, bombordo - lado direito da embarcação, a vante - fica na frente, a ré - fica atrás', 0),
(359, 90, 'través - ao lado da embarcação, a vante - parte da frente da embarcação, a ré - parte de trás da embarcação', 0),
(360, 90, 'través - bordos da embarcação, boreste - lado direito da embarcação, bombordo - lado esquerdo da embarcação', 0),
(361, 91, 'orientar o navegador a se deslocar com sua embarcação, em determinada área, apresentando tudo que for necessário para sua segurança', 1),
(362, 91, 'orientar o deslocamento de um navegador, em águas interiores', 0),
(363, 91, 'orientar o deslocamento de um navegador, vindo de alto-mar', 0),
(364, 91, 'orientar a navegação do globo terrestre, mostrando os diversos trechos das diversas costas dos continentes', 0),
(365, 92, 'as latitudes e longitudes deste ponto', 1),
(366, 92, 'a direção e o sentido do seu movimento', 0),
(367, 92, 'as marcações nas escalas laterais da carta', 0),
(368, 92, 'as marcações nas escalas superior e inferior da carta', 0),
(369, 93, 'escala', 0),
(370, 93, 'pontos notáveis', 0),
(371, 93, 'rosa dos ventos', 1),
(372, 93, 'marcas de profundidade', 0),
(373, 94, 'direção que um navegador toma para, a partir de um ponto qualquer, chegar a outro. Régua paralela', 1),
(374, 94, 'direção que um navegador toma entre dois pontos. Esquadro de navegação', 0),
(375, 94, 'distância entre dois pontos na carta náutica. Régua paralela', 0),
(376, 94, 'distância entre dois pontos na carta náutica. Compasso de navegação', 0),
(377, 95, 'escala de longitude, milha náutica', 0),
(378, 95, 'escala de latitude, milha náutica', 1),
(379, 95, 'escala de longitude, metros por segundos', 0),
(380, 95, 'escala de latitude, metros por segundo ', 0),
(381, 96, 'régua paralela', 0),
(382, 96, 'esquadro de navegação', 0),
(383, 96, 'sextante', 0),
(384, 96, 'compasso de navegação', 1),
(385, 97, 'com o título da carta e demais informações de frente para o navegador, de forma que ele possa ler e identificar as informações, nela contidas', 1),
(386, 97, 'com as escalas de latitude voltadas para cima ou para baixo, em relação à mesa em que se vai colocar a carta', 0),
(387, 97, 'com a informação das laterais da carta voltadas para cima', 0),
(388, 97, 'de qualquer forma pois, a carta deve informar ao navegador, em diversas situações, o posicionamento da embarcação e, portanto, variará com estas diferenças', 0),
(389, 98, 'para padronizar a utilização e a interpretação das informações contidas nas cartas náuticas', 1),
(390, 98, 'para facilitar somente a identificação de pedras, perigos, cascos soçobrados, bancos de areia e altos fundos ', 0),
(391, 98, 'para facilitar somente a identificação de pontos notáveis, tais como: igrejas, construções, estações de rádio e morros', 0),
(392, 98, 'para auxiliar o navegador somente na identificação das informações de qualidade do fundo, setores de visibilidade de faróis, linhas isobatiméticas e isogônicas', 0),
(393, 99, 'pequena escala', 0),
(394, 99, 'grande escala', 1),
(395, 99, 'escala com grande denominador', 0),
(396, 99, 'escala média', 0),
(397, 100, 'a relação de uma milha náutica na carta, é, na realidade, 3000 vezes maior', 0),
(398, 100, 'a relação de um metro, na carta náutica, é 3000 vezes maior', 0),
(399, 100, 'a carta é reduzida 3 vezes o tamanho do trecho real', 0),
(400, 100, 'a carta reduz, o trecho nela mostrado, em 3000 vezes', 1),
(401, 101, 'medidas em centímetros e décimos', 0),
(402, 101, 'medidas a partir de um ponto de referência', 0),
(403, 101, 'medidas em quilômetros', 0),
(404, 101, 'medidas em metros e decímetros', 1),
(405, 102, 'retas paralelas, na carta náutica, às escalas das extremidades superior e inferior', 1),
(406, 102, 'retas paralelas, na carta náutica, às escalas das laterais', 0),
(407, 102, 'retas paralelas ao meridiano principal, na carta náutica', 0),
(408, 102, 'curvas que formam os círculos máximos, na carta náutica', 0),
(409, 103, 'retas paralelas, na carta náutica, às escalas laterais das extremidades superior e inferior', 0),
(410, 103, 'retas paralelas, na carta náutica, às escalas das laterais', 1),
(411, 103, 'retas paralelas ao equador, na carta náutica', 0),
(412, 103, 'curvas que formam os círculos máximos, que passam pelos pontos a leste e a oeste, na carta náutica', 0),
(413, 104, 'a partir do paralelo mais próximo, tirar a distância até o ponto e transportá-la com o auxílio da régua paralela ou do compasso de navegação, até a escala de latitude e ler o valor', 1),
(414, 104, 'a partir do ponto, determinar a distância até o paralelo mais próximo e subtrair o valor em milhas', 0),
(415, 104, 'a partir do meridiano mais próximo, tirar a distância até o ponto e transportar, com o auxílio da régua paralela ou do compasso de navegação até a escala de latitudes e ler o valor ', 0),
(416, 104, 'a partir do ponto, verificar a declinação na rosa-dos-ventos e aplicar a sua correção, para somar ou subtrair, do valor em graus, do paralelo mais próximo', 0),
(417, 105, 'a partir do paralelo mais próximo, tirar a distância até o ponto e transportá-la, com o auxílio da régua paralela ou do compasso de navegação, até a escala de latitudes e ler o valor', 0),
(418, 105, 'a partir do ponto, determinar a distância até o paralelo mais próximo e subtrair o valor em milhas', 0),
(419, 105, 'a partir do meridiano mais próximo, tirar a distância até o ponto e transportar, com o auxílio da régua paralela ou do compasso de navegação, até a escala de longitudes e ler o valor', 1),
(420, 105, 'a partir do ponto, verificar a declinação na rosa-dos-ventos e aplicar sua correção, para somar ou subtrair, do valor em graus, do paralelo mais próximo', 0),
(421, 106, 'ser aplicada ao rumo da agulha, junto com seu desvio, para se determinar o rumo verdadeiro, na carta náutica', 1),
(422, 106, 'ser aplicada ao norte da agulha, para se determinar o norte verdadeiro', 0),
(423, 106, 'ser aplicada ao rumo da embarcação, para se determinar o rumo no fundo', 0),
(424, 106, 'determinar a variação da agulha giroscópica', 0),
(425, 107, 'a variação da agulha', 0),
(426, 107, 'a variação anual', 0),
(427, 107, 'o aumento anual', 1),
(428, 107, 'o desvio da agulha', 0),
(429, 108, 'Carta Internacional de Símbolos', 0),
(430, 108, 'Carta de Símbolos Náuticos', 0),
(431, 108, 'Carta 12.000, Símbolos, Abreviaturas e Termos', 1),
(432, 108, 'Código Internacional de Sinais', 0),
(433, 109, 'fazer manutenção constantes nas instalações elétricas', 0),
(434, 109, 'fumar em local proibido', 1),
(435, 109, 'apagar bem os cigarros', 0),
(436, 109, 'estocar botijões de gás longe de locais quentes ou com risco de chamas', 0),
(437, 110, 'houver o combustível, o comburente e o agente extintor', 0),
(438, 110, 'ocorrer a presença de três elementos do triângulo do fogo: o oxigênio, o comburente e a temperatura de ignição', 1),
(439, 110, 'ocorrer a presença de três elementos do triângulo do fogo: o oxigênio, o combustível e o comburente', 0),
(440, 110, 'ocorrer a presença de três elementos do triângulo do fogo: o comburente, o combustível e a temperatura de ignição', 0),
(441, 111, 'a queima de substâncias sólidas, líquidas ou gasosas, na presença de ar atmosférico', 1),
(442, 111, 'a queima de substâncias combustíveis, na presença de altas temperaturas ambientais', 0),
(443, 111, 'a reação de combustível e oxigênio, ao se encontrarem', 0),
(444, 111, 'a elevação de temperatura, devido a reação de um elemento combustível com outro', 0),
(445, 112, 'elemento da natureza capaz de se queimar na presença de oxigênio', 1),
(446, 112, 'elemento que reage com outros, para evitar a combustão', 0),
(447, 112, 'elemento que oferece risco de explodir', 0),
(448, 112, 'elemento natural, que gera altas temperaturas, ao entrar em contato com o ar atmosférico', 0),
(449, 113, 'sólido', 0),
(450, 113, 'líquido na atmosfera', 0),
(451, 113, 'oxigênio', 1),
(452, 113, 'um agente extintor', 0),
(453, 114, 'mangueira e esguinchos', 0),
(454, 114, 'sistemas fixos de CO2', 0),
(455, 114, 'ampolas de halon', 0),
(456, 114, 'extintores portáteis', 1),
(457, 115, 'equipamentos de combate a incêndio, que utilizam os agentes extintores para apagar o fogo', 1),
(458, 115, 'equipamentos de combate a incêndio, que utilizam o comburente para apagar o fogo', 0),
(459, 115, 'equipamentos de apoio ao controle de avarias', 0),
(460, 115, 'equipamentos de extinção de incêndios, somente da classe A', 0),
(461, 116, 'me mantenho a barlavento das chamas', 1),
(462, 116, 'me mantenho a bombordo', 0),
(463, 116, 'me mantenho a meia embarcação', 0),
(464, 116, 'me mantenho na alheta de boreste', 0),
(465, 117, 'as substâncias que auxiliam o controle de vazamentos a bordo', 0),
(466, 117, 'as substâncias que extinguem incêndios', 1),
(467, 117, 'as substâncias que alimentam as chamas', 0),
(468, 117, 'as substâncias que formam um lado do triângulo do fogo', 0),
(469, 118, 'equipamentos e redes elétricas', 0),
(470, 118, 'líquidos inflamáveis', 0),
(471, 118, 'materiais sólidos inflamáveis', 1),
(472, 118, 'paióis de tinta', 0),
(473, 119, 'líquidos inflamáveis', 0),
(474, 119, 'materiais sólidos inflamáveis', 1),
(475, 119, 'gases', 0),
(476, 119, 'materiais elétricos', 0),
(477, 120, 'que ocorre na presença de agente extintor', 0),
(478, 120, 'que ocorre em materiais sólidos inflamáveis', 0),
(479, 120, 'que ocorre em materiais elétricos', 0),
(480, 120, 'que ocorre em líquidos inflamáveis', 1),
(481, 121, 'que ocorre na presença de agente extintor', 0),
(482, 121, 'que ocorre em materiais sólidos inflamáveis', 0),
(483, 121, 'que ocorre em materiais elétricos', 1),
(484, 121, 'que ocorre em líquidos inflamáveis', 0),
(485, 122, 'incêndios da classe A', 0),
(486, 122, 'incêndios de líquidos inflamáveis', 0),
(487, 122, 'incêndios em materiais elétricos', 1),
(488, 122, 'incêndios em materiais sólidos inflamáveis', 0),
(489, 123, 'incêndios da classe A', 0),
(490, 123, 'incêndios de líquidos inflamáveis', 1),
(491, 123, 'incêndios em materiais elétricos', 0),
(492, 123, 'incêndios em materiais sólidos inflamáveis', 0),
(493, 124, 'virar o extintor e direcioná-lo a base da chama', 0),
(494, 124, 'apertar o gatilho e direcioná-lo para a base das chamas, invertendo sua posição', 1),
(495, 124, 'puxar o pino de segurança e inverter sua posição', 0),
(496, 124, 'jogá-lo sobre o fogo', 0),
(497, 125, 'retirar o gatilho e apertar a trava de segurança', 0),
(498, 125, 'direcioná-lo contra as chamas, invertendo sua posição', 0),
(499, 125, 'pressionar o gatilho e dirigir o jato contra as chamas', 0),
(500, 125, 'retirar o pino de segurança, segurar o difusor e apertar o gatilho, direcionando o jato, para a base do fogo', 1),
(501, 126, 'virar o extintor, com a tampa para baixo, e dirigir o jato sobre a base das chamas', 1),
(502, 126, 'apertar o gatilho e direcionar o jato para as chamas', 0),
(503, 126, 'retirar o pino de segurança, e direcioná-lo sobre os equipamentos elétricos', 0),
(504, 126, 'apertar o gatilho e direcioná-lo sobre os líquidos inflamáveis', 0),
(505, 127, 'removemos para longe o material inflamável e resfriamos os locais próximos', 1),
(506, 127, 'agitamos as chamas no local e cercamos com barreiras', 0),
(507, 127, 'jogamos o material sólido sobre as chamas espalhadas em grandes áreas', 0),
(508, 127, 'abrimos portas, escotilhas e vigias e deixamos ventilar o ambiente', 0),
(509, 128, 'evitar dirigir o jato diretamente nas chamas para não agitá-las', 0),
(510, 128, 'evitar o contato direto do jato com a pele e os olhos', 1),
(511, 128, 'evitar utilizá-lo em equipamentos energizados e ter cuidado ao inverter sua posição', 0),
(512, 128, 'verificar o nível de agente extintor, abrindo sua tampa, e evitar de segurar no difusor para não queimar a mão', 0),
(513, 129, 'acomodações', 1),
(514, 129, 'líquidos inflamáveis', 0),
(515, 129, 'equipamentos de navegação', 0),
(516, 129, 'motores elétricos', 0),
(517, 130, 'locais fechados e seguros', 0),
(518, 130, 'paióis de materiais, atrás de equipamentos pesados', 0),
(519, 130, 'locais de fácil acesso e de risco de incêndio', 1),
(520, 130, 'locais de acesso restrito da embarcação', 0),
(521, 131, 'CO2', 0),
(522, 131, 'água', 0),
(523, 131, 'espuma', 1),
(524, 131, 'tanto faz', 0),
(525, 132, 'CO2', 1),
(526, 132, 'água', 0),
(527, 132, 'espuma', 0),
(528, 132, 'tanto faz', 0),
(529, 133, 'baldes d’água', 1),
(530, 133, 'cobertores de fibra sintética', 0),
(531, 133, 'madeira', 0),
(532, 133, 'qualquer líquido disponível a bordo', 0),
(533, 134, 'em bom estado de conservação visual', 0),
(534, 134, 'com revisões anuais dentro da validade', 1),
(535, 134, 'em número determinado, de acordo com a lotação da embarcação', 0),
(536, 134, 'próximos ao convés principal', 0),
(537, 135, 'documento normativo da DPC', 1),
(538, 135, 'relação do tamanho da embarcação', 0),
(539, 135, 'relação ao tipo da embarcação', 0),
(540, 135, 'relação a lotação de pessoas a bordo', 0),
(541, 136, 'sistemas com difusores fixos', 1),
(542, 136, 'sistemas acoplados à rede de aguada', 0),
(543, 136, 'sistemas com mangueira e esguinchos', 0),
(544, 136, 'sistemas existentes apenas em navios de grande porte', 0),
(545, 137, 'sistemas fixos de geração de gás', 0),
(546, 137, 'sistemas móveis de pó especial', 0),
(547, 137, 'sistemas fixos de agentes extintores', 1),
(548, 137, 'sistemas acoplados à rede de incêndio', 0),
(549, 138, 'cobertores, gás hélio e CO2', 0),
(550, 138, 'água, CO2 e espuma', 1),
(551, 138, 'gás hélio e gasolina', 0),
(552, 138, 'gases em geral', 0),
(553, 139, 'uma massagem cardíaca externa', 0),
(554, 139, 'uma respiração boca-a-boca', 1),
(555, 139, 'uma verificação na menina dos olhos', 0),
(556, 139, 'um aquecimento no corpo', 0),
(557, 140, 'se a vítima está com pulso fraco', 0),
(558, 140, 'se a vítima está com o coração batendo', 0),
(559, 140, 'se existem corpos estranhos na sua boca', 1),
(560, 140, 'se a vítima está com a menina dos olhos dilatada', 0),
(561, 141, '10 a 15', 1),
(562, 141, '15 a 20', 0),
(563, 141, '20 a 30', 0),
(564, 141, 'mais de trinta', 0),
(565, 142, 'continuar a respiração até ela respirar sozinha', 0),
(566, 142, 'fazer massagem cardíaca externa', 1),
(567, 142, 'aquecer a vítima', 0),
(568, 142, 'esperar alguns segundos e verificar novamente', 0),
(569, 143, 'a massagem cardíaca externa', 1),
(570, 143, 'a respiração boca a boca', 0),
(571, 143, 'a traqueostomia', 0),
(572, 143, 'o aquecimento do corpo', 0),
(573, 144, 'palidez', 0),
(574, 144, 'abaixamento rápido da temperatura do corpo', 0),
(575, 144, 'menina dos olhos dilatada', 1),
(576, 144, 'ruborização da face', 0),
(577, 145, 'respiração boca a boca', 0),
(578, 145, 'massagem nos punhos', 0),
(579, 145, 'aquecimento do corpo', 0),
(580, 145, 'murro forte no peito', 1),
(581, 146, 'continuar a respiração boca a boca', 1),
(582, 146, 'continuar uma massagem com menos intensidade ', 0),
(583, 146, 'aquecer a vítima imediatamente', 0),
(584, 146, 'dar alimentos e água a vítima', 0),
(585, 147, '30 vezes por minuto', 0),
(586, 147, '60 vezes por minuto', 0),
(587, 147, '69 vezes por segundo', 0),
(588, 147, '69 vezes por minuto', 1),
(589, 148, 'realizar movimentos intercalados, 8 massagens cardíacas e uma respiração boca a boca', 1),
(590, 148, 'realizar movimentos intercalados, 1 massagem cardíaca e 8 respirações boca a boca', 0),
(591, 148, 'só realizar massagem cardíaca, após a vítima voltar a respirar', 0),
(592, 148, 'só realizar respiração boca a boca, após o coração da vítima começar a bater', 0),
(593, 149, 'deixar a cabeça da vítima na posição lateral', 0),
(594, 149, 'deixar a cabeça da vítima na posição normal', 0),
(595, 149, 'deixar a cabeça da vítima voltada para trás', 1),
(596, 149, 'deixar a cabeça da vítima voltada para frente', 0),
(597, 150, 'tábua, papelão ou jornal grosso', 1),
(598, 150, 'material flexível', 0),
(599, 150, 'material de borracha sintética', 0),
(600, 150, 'tiras de pano amarradas no pescoço', 0),
(601, 151, 'tala', 1),
(602, 151, 'material isolante', 0),
(603, 151, 'torniquete', 0),
(604, 151, 'tampão', 0),
(605, 152, 'esticado', 0),
(606, 152, 'na posição que quebrou', 0),
(607, 152, 'dobrado', 1),
(608, 152, 'em qualquer posição', 0),
(609, 153, 'esticada', 1),
(610, 153, 'na posição que quebrou', 0),
(611, 153, 'dobrado', 0),
(612, 153, 'em qualquer posição', 0),
(613, 154, 'inclinada', 0),
(614, 154, 'esticada', 0),
(615, 154, 'a mais natural possível', 1),
(616, 154, 'tanto faz', 0),
(617, 155, 'realizar a imobilização rapidamente e, logo após, removê-la do local', 0),
(618, 155, 'removê-la primeiro do local de risco', 1),
(619, 155, 'realizar a imobilização independente do risco', 0),
(620, 155, 'dar combate ao risco primeiro, deixando a vítima esperando', 0),
(621, 156, 'ser atendida de imediato, com remoção do local para lugar arejado', 0),
(622, 156, 'ser afastada do local de risco, antes de aquecermos seu corpo', 0),
(623, 156, 'ser retirada do local, puxando-a do contato com a corrente elétrica', 0),
(624, 156, 'ser afastada do contato com a corrente elétrica, utilizando material não condutor de eletricidade', 1),
(625, 157, 'pedaço de madeira', 0),
(626, 157, 'peça de metal', 1),
(627, 157, 'pedaço de pneu', 0),
(628, 157, 'peça de porcelana', 0),
(629, 158, 'aquecimento do seu corpo', 0),
(630, 158, 'dar água e deixá-la sem roupas, num local arejado', 0),
(631, 158, 'realizar respiração boca a boca e massagem cardíaca externa', 1),
(632, 158, 'lavar a vítima com água e cobri-la com panos limpos', 0),
(633, 159, 'lavar com água e evitar romper a bolha', 1),
(634, 159, 'deixar secar e colocar panos limpos', 0),
(635, 159, 'furar as bolhas e desinfetá-las com álcool', 0),
(636, 159, 'cobrir com pano disponível', 0),
(637, 160, 'aplicar sobre elas pó de café ou açúcar', 0),
(638, 160, 'colocar manteiga ou banha', 0),
(639, 160, 'aplicar sobre elas álcool para desinfetar', 0),
(640, 160, 'passar mercúrio cromo ou mertiolate', 1),
(641, 161, 'tirar a roupa da vítima', 1),
(642, 161, 'dar líquidos', 0),
(643, 161, 'cobrir a vítima com panos ou cobertor', 0),
(644, 161, 'remover a vítima do local', 0),
(645, 162, 'grande perda de sangue', 1),
(646, 162, 'desmaio temporário', 0),
(647, 162, 'ruptura da pele', 0),
(648, 162, 'aparecimento de bolhas e manchas isoladas na pele', 0),
(649, 163, 'preparar uma tala', 0),
(650, 163, 'cobri-la com panos limpos ', 0),
(651, 163, 'abaixar a parte do corpo ferida', 0),
(652, 163, 'pressionar o local com um pano grosso', 1),
(653, 164, 'imobilizar membros fraturados', 0),
(654, 164, 'estancar hemorragias muito grandes', 1),
(655, 164, 'estancar pequenas hemorragias', 0),
(656, 164, 'tratar pequenas queimaduras locais', 0),
(657, 165, 'utilizando um pano largo e um pedaço de madeira que se fixará ao pano, por meio de um nó e torcendo a madeira, a pressão interromperá a hemorragia', 1),
(658, 165, 'utilizando um pano grande sobre pressão, no local da hemorragia', 0),
(659, 165, 'utilizando uma madeira amarrada no local, por tiras de pano grosso', 0),
(660, 165, 'utilizando qualquer material isolante, para ser aplicado, juntamente com uma pomada antiinflamatória', 0),
(661, 166, 'não cobri-lo', 0),
(662, 166, 'apertá-lo e sempre que a hemorragia não estancar', 0),
(663, 166, 'nunca desapertá-lo', 1),
(664, 166, 'não retirá-lo logo que a hemorragia cesse', 0),
(665, 167, 'não dar líquidos enquanto estiver inconsciente e mantê-la agasalhada', 1),
(666, 167, 'nunca desapertar o torniquete, enquanto a hemorragia estiver ocorrendo', 0),
(667, 167, 'verificar se ela respira e fazer massagem cardíaca externa', 0),
(668, 167, 'desapertar o torniquete, depois de 30 minutos e reapertá-lo independente de ter parado a hemorragia', 0),
(669, 168, 'medidas preventivas de acidentes', 0),
(670, 168, 'medidas emergenciais de prestação de socorro, antes do encaminhamento médico', 1),
(671, 168, 'tratamentos médicos nas emergências de bordo', 0),
(672, 168, 'operações de emergência a vítimas, em acidentes de trânsito', 0),
(673, 169, 'para ser vestido, no caso de ter de abandonar a embarcação, para que o náufrago flutue com ele.', 1),
(674, 169, 'para ser vestido, no caso de incêndio a bordo, como roupa de proteção.', 0),
(675, 169, 'para ser utilizado, como material de controle de avarias, no caso de acidentes com o casco da embarcação.', 0),
(676, 169, 'para ser utilizado como meio de flutuação, quando o passageiro desejar pular na água, para nadar um pouco.', 0),
(677, 170, 'balsa salva-vidas', 0),
(678, 170, 'colete salva-vidas', 0),
(679, 170, 'bóia circular', 0),
(680, 170, 'baleeira', 1),
(681, 171, 'bóia circular', 0),
(682, 171, 'colete salva-vidas', 0),
(683, 171, 'balsa', 1),
(684, 171, 'bote rígido', 0),
(685, 172, 'amarrado ao corpo, com a parte flutuante para frente', 1),
(686, 172, 'amarrado ao corpo, com a parte flutuante para as costas', 0),
(687, 172, 'conduzido pelo náufrago na mão', 0),
(688, 172, 'jogado na água para o náufrago se apoiar', 0),
(689, 173, 'a todos os passageiros adultos', 0),
(690, 173, 'a todos os passageiros', 0),
(691, 173, 'ao limite máximo de pessoas a bordo', 1),
(692, 173, 'a todos os membros da tripulação', 0),
(693, 174, 'amarrado a embarcação, em local bem fechado, para protegê-lo da ação do tempo.', 0),
(694, 174, 'no convés principal, solto, para ser utilizado em caso de emergência.', 0),
(695, 174, 'num paiol da embarcação ou no compartimento de acomodações', 0),
(696, 174, 'em local de fácil acesso, em caso de necessidade, e nunca, amarrado à embarcação', 1),
(697, 175, 'um cabo flutuante com alça de mão', 1),
(698, 175, 'uma retinida com pinha na ponta', 0),
(699, 175, 'um foguete pirotécnico', 0),
(700, 175, 'uma caixa de primeiros socorros', 0),
(701, 176, 'no caso de incêndio a bordo', 0),
(702, 176, 'no caso de emergência a bordo', 0),
(703, 176, 'para abandonar a embarcação, em caso de emergência', 1),
(704, 176, 'para lazer em proximidades de praias', 0),
(705, 177, 'já estiverem todos embarcados na balsa', 0),
(706, 177, 'a embarcação estiver afundando', 1),
(707, 177, 'a balsa estiver pronta para navegar', 0),
(708, 177, 'a balsa estiver furada', 0),
(709, 178, 'fazer peso de um lado só, para ela não virar', 1),
(710, 178, 'utilizar o lado que estiver com muito vento', 0),
(711, 178, 'pressionar a borda pois ela pode furar', 0),
(712, 178, 'fazê-lo com pessoas subindo ao mesmo tempo, de lados opostos', 0),
(713, 179, 'a favor da correnteza', 0),
(714, 179, 'sobre o óleo, pois este, vai amaciar a queda', 0),
(715, 179, 'contra a correnteza', 1),
(716, 179, 'sempre de costas', 0),
(717, 180, 'nadar na superfície, com o rosto sempre para cima', 0),
(718, 180, 'nadar de costa para as ondas ou marolas', 0),
(719, 180, 'nadar contra a correnteza e, se for o caso, por baixo d’água, até afastarmos o risco de óleo, na superfície', 1),
(720, 180, 'nadar espalhando o óleo, que esteja pegando fogo, e respirando o mais rápido que pudermos', 0),
(721, 181, 'nadando sempre em direção a costa', 0),
(722, 181, 'nadando a favor da correnteza', 1),
(723, 181, 'deixando-a ser carregada pela correnteza', 0),
(724, 181, 'nadando por baixo d’água', 0),
(725, 182, 'toras de madeira, flutuando', 0),
(726, 182, 'troncos de árvores, flutuando', 0),
(727, 182, 'pedras e bancos de areia', 0),
(728, 182, 'correntezas dos rios e marolas', 1),
(729, 183, 'afundar a marca do limite mínimo de flutuação', 1),
(730, 183, 'colocar mais peso na parte de baixo do que na parte de cima da embarcação', 0),
(731, 183, 'colocar pesos pequenos, no convés principal', 0),
(732, 183, 'dividir os pesos entre as laterais da embarcação', 0),
(733, 184, 'deixar que as pessoas se concentrem na proa ou na popa da embarcação', 0),
(734, 184, 'exceder o limite permitido de pessoas a bordo', 1),
(735, 184, 'colocar pesos no fundo da embarcação', 0),
(736, 184, 'permitir que pessoas sem colete embarquem a bordo', 0),
(737, 185, 'verificar a s luzes de navegação.', 0),
(738, 185, 'verificar os equipamentos de salvatagem', 0),
(739, 185, 'verificar os equipamentos de combate a incêndio', 0),
(740, 185, 'verificar se a embarcação está com as acomodações limpas e arrumadas', 1),
(741, 186, 'estabilidade da embarcação', 1),
(742, 186, 'estanqueidade da embarcação', 0),
(743, 186, 'flutuabilidade direcional', 0),
(744, 186, 'economia de combustível', 0),
(745, 187, 'no convés principal', 0),
(746, 187, 'num armário da cabine de comando', 0),
(747, 187, 'em local de fácil retirada', 1),
(748, 187, 'na proa e na popa da embarcação', 0),
(749, 188, 'as pernas abertas, a mão direita no nariz e a mão esquerda no ombro', 0),
(750, 188, 'os pés juntos e as pernas dobradas', 0),
(751, 188, 'as pernas esticadas e os pés juntos', 1),
(752, 188, 'a mão direita no nariz e os pés separados', 0),
(753, 189, 'como encosto', 0),
(754, 189, 'para fazer demonstrações', 1),
(755, 189, 'com travesseiro', 0),
(756, 189, 'como brinquedo', 0),
(757, 190, 'pneus', 0),
(758, 190, 'latões ou barris', 0),
(759, 190, 'toras ou pedaços grande de madeira', 0),
(760, 190, 'coletes salva-vidas defeituosos', 1),
(761, 191, 'deite o afogado de lado, para vomitar a água que bebeu, tire a roupa molhada e aqueça-o', 1),
(762, 191, 'deite o afogado de barriga para cima, para ele poder respirar melhor e, nunca lhe dê bebidas', 0),
(763, 191, 'deite o afogado de lado e faça-o vomitar, depois aqueça-o com um cobertor', 0),
(764, 191, 'deite o afogado de lado e faça respiração boca a boca', 0),
(765, 192, 'deitá-lo de lado, limpar sua boca de objetos que obstruam sua respiração e realizar a respiração boca a boca', 1),
(766, 192, 'deitá-lo de barriga para baixo e fazer massagem nas costas', 0),
(767, 192, 'deitá-lo de lado e iniciar a massagem cardíaca externa', 0),
(768, 192, 'deitá-lo de frente e começar a massagem cardíaca externa', 0),
(769, 193, 'uma respiração boca a boca', 0),
(770, 193, 'uma massagem cardíaca externa', 1),
(771, 193, 'uma verificação na boca do afogado', 0),
(772, 193, 'a retirada da sua roupa molhada', 0),
(773, 194, 'piranha', 0),
(774, 194, 'candiru', 0);
INSERT INTO `opcao` (`id`, `pergunta_id`, `titulo`, `correta`) VALUES
(775, 194, 'jacaré', 0),
(776, 194, 'tubarão', 1),
(777, 195, 'suas pupilas e seu rabo', 1),
(778, 195, 'seu rabo e sua coloração', 0),
(779, 195, 'suas pupilas e sua coloração', 0),
(780, 195, 'seu rabo e seu comprimento', 0),
(781, 196, 'jibóia', 0),
(782, 196, 'coral', 0),
(783, 196, 'd’água', 0),
(784, 196, 'sucuri', 1),
(785, 197, 'cobras', 0),
(786, 197, 'piranhas', 0),
(787, 197, 'arraias', 1),
(788, 197, 'rãs', 0),
(789, 198, 'com seus pertences pessoais e muita roupa', 0),
(790, 198, 'com roupas adequadas e material de salvatagem', 1),
(791, 198, 'com roupas de mergulho e seus pertences pessoais', 0),
(792, 198, 'com material de salvatagem e roupas pesadas', 0),
(793, 199, 'Regulamento de Segurança do Tráfego Aquaviário em águas sob Jurisdição Nacional', 1),
(794, 199, 'Regulamento de Segurança do Tráfego Aquaviário em águas Internacionais', 0),
(795, 199, 'Regulamento de Segurança do Tráfego Aquaviário aplicado somente as embarcações de esporte e recreio', 0),
(796, 199, 'Regulamento Internacional de Segurança do Tráfego Aquaviário', 0),
(797, 200, 'em águas abrigadas', 0),
(798, 200, 'à vista de terra', 0),
(799, 200, 'em alto mar', 1),
(800, 200, 'nas proximidades dos portos', 0),
(801, 201, 'uma navegação em águas interiores', 0),
(802, 201, 'uma navegação de apoio marítimo', 0),
(803, 201, 'uma navegação de cabotagem', 0),
(804, 201, 'uma navegação de longo curso', 1),
(805, 202, 'uma navegação em águas interiores', 0),
(806, 202, 'uma navegação de apoio portuário', 1),
(807, 202, 'uma navegação de cabotagem', 0),
(808, 202, 'uma navegação de longo curso', 0),
(809, 203, 'marítimos, fluviários, pescadores, mergulhadores, práticos, seguradoras e agentes de manobra e docagem', 0),
(810, 203, 'marítimos, fluviários, pescadores, mergulhadores, práticos e agentes de manobra e docagem', 1),
(811, 203, 'marítimos, fluviários e práticos, somente', 0),
(812, 203, 'arrais-amador, mestre amador e capitão amador', 0),
(813, 204, 'somente ao aquaviário', 0),
(814, 204, 'somente ao amador embarcado', 0),
(815, 204, 'somente ao prático', 0),
(816, 204, 'ao aquaviário, ou amador embarcado e ao prático', 1),
(817, 205, '12 meses', 1),
(818, 205, '8 meses', 0),
(819, 205, '4 meses', 0),
(820, 205, '2 meses', 0),
(821, 206, '24 meses', 0),
(822, 206, '12 meses', 1),
(823, 206, '10 meses', 0),
(824, 206, '2 meses', 0),
(825, 207, 'Normas da Autoridade Marítima que complementam o ''R-LESTA''', 1),
(826, 207, 'Normas da DPC que complementam, o ''R-LESTA''', 0),
(827, 207, 'Normas das Marinas e Entidades Desportivas Náuticas', 0),
(828, 207, 'normas de um comandante de uma embarcação', 0),
(829, 208, 'a menos de (200) metros de instalações militares e (500) metros das plataformas de prospecção de petróleo', 1),
(830, 208, 'usinas hidrelétricas, termoelétricas, nucleoelétricas e fundeadouros de navios mercantes', 0),
(831, 208, 'canais de acesso aos portos e proximidades das instalações do porto', 0),
(832, 208, 'fundeadouros de embarcações de esporte e recreio', 0),
(833, 209, 'navegar velozmente', 0),
(834, 209, 'navegar sem combustível', 0),
(835, 209, 'exceder a lotação autorizada', 1),
(836, 209, 'deixar de exibir as luzes atracada no cais', 0),
(837, 210, 'de mar aberto', 0),
(838, 210, 'interior', 0),
(839, 210, 'apoio marítimo', 0),
(840, 210, 'longo curso', 1),
(841, 211, 'arrais amador', 0),
(842, 211, 'mestre amador', 0),
(843, 211, 'capitão amador', 0),
(844, 211, 'Capitão dos Portos', 1),
(845, 212, 'na popa da embarcação', 1),
(846, 212, 'na proa da embarcação', 0),
(847, 212, 'no mastro de vante', 0),
(848, 212, 'no paiol das bandeiras', 0),
(849, 213, 'GRANDE GALA: 07 de setembro e 15 de novembro', 0),
(850, 213, 'PEQUENA GALA: 1? de janeiro, 21 de abril, 1? de maio, 11 de junho, 19 de novembro, 13 de dezembro e 25 de dezembro', 0),
(851, 213, 'JUNINO: 24 de junho', 1),
(852, 213, 'FUNERAL: 2 de novembro', 0),
(853, 214, 'a cassação de sua habilitação', 1),
(854, 214, 'a cassação da habilitação de quem foi avistado na condução', 0),
(855, 214, 'a notificação do amador', 0),
(856, 214, 'a perda de pontos na habilitação', 0),
(857, 215, '12 dias úteis', 0),
(858, 215, '15 dias úteis', 1),
(859, 215, '30 dias úteis', 0),
(860, 215, '60 dias úteis', 0),
(861, 216, '20 m da área onde existam banhistas', 0),
(862, 216, '50 m da área onde existam banhistas', 0),
(863, 216, '150 m da área onde existam banhistas', 0),
(864, 216, '200 m da área onde existam banhistas', 1),
(865, 217, 'proa', 0),
(866, 217, 'popa', 0),
(867, 217, 'borda', 1),
(868, 217, 'convés', 0),
(869, 218, '8 anos', 0),
(870, 218, '10 anos', 0),
(871, 218, '16 anos', 0),
(872, 218, '18 anos', 1),
(873, 219, 'habilitação', 1),
(874, 219, 'conhecerem o local', 0),
(875, 219, 'saberem nadar', 0),
(876, 219, 'terem tripulação', 0);

-- --------------------------------------------------------

--
-- Estrutura da tabela `pergunta`
--

DROP TABLE IF EXISTS `pergunta`;
CREATE TABLE IF NOT EXISTS `pergunta` (
	`id` int(11) NOT NULL AUTO_INCREMENT,
	`prova_id` int(11) NOT NULL,
	`titulo` text NOT NULL,
	PRIMARY KEY (`id`),
	KEY `prova_id` (`prova_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Extraindo dados da tabela `pergunta`
--

INSERT INTO `pergunta` (`id`, `prova_id`, `titulo`) VALUES
(1, 1, 'Qual a finalidade do RIPEAM?'),
(2, 1, 'Na situação de ''roda a roda'', ou seja, _____ as embarcações deverão manobrar da seguinte forma:'),
(3, 1, 'Na situação de rumos cruzados, quem tem preferência de passagem?'),
(4, 1, 'Uma embarcação alcançando a outra tem preferência de passagem, ou não, e como deve se proceder tal manobra?'),
(5, 1, 'Um veleiro e uma lancha vinham navegando em rumos cruzados, tendo preferência de passagem, o veleiro não manobrou e esperou que a lancha guinasse, enquanto se aproximava rapidamente dela. Houve uma colisão das duas embarcações. Podemos concluir que:'),
(6, 1, 'Toda manobra deverá ser feita de que forma?'),
(7, 1, 'No rio onde duas lanchas de esporte e recreio navegam em rumos opostos como deverá ser a manobra e quem tem a preferência?'),
(8, 1, 'Em canais estreitos as embarcações devem:'),
(9, 1, 'Num canal ou rio, principalmente estreitos, a embarcação maior tem em relação à embarcação miúda:'),
(10, 1, 'O que vem a ser velocidade de segurança e o que devemos fazer quando cruzamos com outras embarcações atracadas ou fundeadas ou mesmo localizadas às margens dos rios ou canais?'),
(11, 1, 'Com relação a preferência de manobra, uma embarcação à vela deverá manter-se fora do caminho de todas as listadas abaixo, exceto:'),
(12, 1, 'As luzes de navegação mais comuns, em embarcações de esporte e recreio são:'),
(13, 1, 'Os sinais sonoros que podem ser emitidos por apitos, buzinas ou ainda sinos, são utilizados em três situações:'),
(14, 1, 'Um apito curto significa:'),
(15, 1, 'Dois apitos curtos significam:'),
(16, 1, 'Três apitos curtos significam:'),
(17, 1, 'Dois apitos longos seguidos de dois curtos significam:'),
(18, 1, 'O holofote pode ser utilizado:'),
(19, 1, 'Cinco apitos curtos ou mais significam:'),
(20, 1, 'Um apito longo de dois em dois minutos significa:'),
(21, 1, 'Dois apitos longos de dois em dois minutos significam:'),
(22, 1, 'Uma embarcação sem governo tem preferência em relação à:'),
(23, 1, 'Uma embarcação à vela tem preferência em relação à:'),
(24, 1, 'Uma embarcação com uma luz branca onde melhor possa ser vista está:'),
(25, 1, 'Embarcação com reboque de menos de 200 metros de comprimento deverá exibir:'),
(26, 1, 'Embarcação com reboque de mais de 200 metros de comprimento deve exibir:'),
(27, 1, 'Se eu avistar uma embarcação de grande porte, à noite, exibindo uma luz encarnada (vermelha) no alto do mastro, devo tomar mais cuidado com qualquer possibilidade de aproximação pois:'),
(28, 1, 'Se durante o dia eu avistar uma embarcação com um balão preto no mastro , ela deverá estar:'),
(29, 1, 'Em curvas de rios ou canais estreitos, onde a visibilidade é prejudicada, eu posso dar:'),
(30, 1, 'O apito curto tem a duração de:'),
(31, 1, 'O apito longo tem a duração de:'),
(32, 1, 'A forma mais correta de cruzar com outra embarcação vindo em sentido contrário é:'),
(33, 1, 'As situações abaixo são as que eu utilizo as luzes de navegação, com exceção de uma:'),
(34, 1, 'Na ausência de apito, a embarcação poderá utilizar:'),
(35, 1, 'Embarcações de esporte e recreio, sem propulsão a motor, com menos de 5 metros de comprimento estão:'),
(36, 1, 'São sinais de perigo, exceto:'),
(37, 1, 'Uma luz intermitente amarela cruzando o canal, à noite, poderá ser:'),
(38, 1, 'Uma embarcação de esporte e recreio deverá evitar cruzar uma via de tráfego, tanto quanto possível, porém, se for necessário tal manobra, deverá fazer:'),
(39, 1, 'As luzes de bordos, de mastro e de alcançado são:'),
(40, 1, 'Dois apitos longos seguidos de um curto significam:'),
(41, 1, 'É um fator que não altera nas condições de manobra da embarcação:'),
(42, 1, 'Com relação ao leme, podemos dizer que é uma:'),
(43, 1, 'Com relação ao hélice, podemos dizer que é uma:'),
(44, 1, 'As âncoras são, peças metálicas, capazes de:'),
(45, 1, 'O que são amarras?'),
(46, 1, 'As fainas de fundear ou suspender devem ser feitas sempre observando:'),
(47, 1, 'Qual das condições abaixo não é necessária para caracterizar um bom fundeadouro?'),
(48, 1, 'Para atracar deve-se, em geral, manobrar da seguinte forma:'),
(49, 1, 'Os cabos principais de amarração são:'),
(50, 1, 'O que são espias e para que servem?'),
(51, 1, 'Havendo corrente no local, que se vai atracar uma lancha, devemos aproveitar seu efeito e:'),
(52, 1, 'Para desatracar a embarcação devemos:'),
(53, 1, 'Com corrente de proa minha desatracação se processa:'),
(54, 1, 'Para que utilizamos a bóia de arinque?'),
(55, 1, 'São partes de uma embarcação:'),
(56, 1, 'Espia que serve para amarrar a embarcação, saindo perpendicularmente ao cais:'),
(57, 1, 'Uma embarcação com um hélice, com rotação direita, com leme a meio, com seguimento e hélice em marcha avante, a proa guinará para:'),
(58, 1, 'Uma embarcação com um hélice, com rotação direita, com leme a meio, com seguimento e hélice em marcha a ré a proa guinará para:'),
(59, 1, 'Uma embarcação com um hélice, com rotação direita, com leme a boreste, com seguimento e hélice em marcha avante, a proa guinará para:'),
(60, 1, 'Uma embarcação com um hélice, com rotação direita, com leme a boreste, com seguimento e hélice em marcha a ré, a proa guinará para:'),
(61, 1, 'Uma embarcação com um hélice, com rotação direita, com leme a bombordo, com seguimento e hélice em marcha avante, a proa guinará para:'),
(62, 1, 'Uma embarcação com um hélice, com rotação direita, com leme a bombordo, com seguimento e hélice em marcha a ré, a proa guinará para:'),
(63, 1, 'Uma embarcação com um hélice, com rotação direita, com leme a meio, partindo do repouso e hélice em marcha a vante, a proa guinará para:'),
(64, 1, 'Uma embarcação com um hélice, com rotação direita, com leme a meio, partindo do repouso e hélice em marcha a ré, a proa guinará para:'),
(65, 1, 'Uma embarcação com um hélice, com rotação direita, com leme a boreste, partindo do repouso e hélice em marcha avante, a proa guinará para:'),
(66, 1, 'Uma embarcação com um hélice, com rotação direita, com leme a boreste, partindo do repouso e hélice em marcha a ré, a proa guinará para:'),
(67, 1, 'Uma embarcação com um hélice, com rotação direita, com leme a bombordo, partindo do repouso e hélice em marcha avante, a proa guinará para:'),
(68, 1, 'Uma embarcação com um hélice, com rotação direita, com leme a bombordo, partindo do repouso e hélice em marcha a ré, a proa guinará para:'),
(69, 1, 'Suspender, em manobra é:'),
(70, 1, 'A âncora mais comum, abordo das embarcações de esporte e recreio, é a:'),
(71, 1, 'São partes do leme:'),
(72, 1, 'Numa atracação, com vento ou corrente perpendicular ao cais, com aproximação a barlavento, deverei aproximar com a embarcação:'),
(73, 1, 'Numa atracação, com vento ou corrente perpendicular ao cais, com aproximação a sotavento, deverei aproximar com a embarcação:'),
(74, 1, 'Numa atracação com vento ou corrente, paralelos ao cais, deverei aproximar com a embarcação:'),
(75, 1, 'Para se largar do cais, sem vento e sem corrente, deverei:'),
(76, 1, 'Para se largar do cais, com vento e corrente pela proa, deverei:'),
(77, 1, 'Para se largar de um cais, com vento e corrente pela popa, deverei:'),
(78, 1, 'Deve-se fundear a embarcação de esporte e recreio, com âncora Danforth, evitando os fundeadouros de tença de:'),
(79, 1, 'Qual a regra simples para se determinar a quantidade de amarra a se largar num fundeio normal?'),
(80, 1, 'Quando houver risco de mau tempo ou o fundeio for muito demorado, qual a regra para se largar a amarra, com segurança da embarcação não sair da posição?'),
(81, 1, 'Para se pegar uma bóia, para amarrarmos uma embarcação, devemos proceder:'),
(82, 1, 'O que vem a ser tença?'),
(83, 1, 'Devemos evitar fundear em área:'),
(84, 1, 'Para se suspender de um fundeadouro, devemos:'),
(85, 1, 'Uma embarcação no visual da minha, para existir, com certeza, o risco de colisão, deverá apresentar a seguinte situação:'),
(86, 1, 'Para fundear devemos:'),
(87, 1, 'Quando numa embarcação de dois hélices, um deles dá atrás e outro adiante, com a mesma rotação, essa embarcação:'),
(88, 1, 'Para se fundear com corrente e vento, deve-se:'),
(89, 1, 'Quando duas embarcações navegam em canal estreito, em rumos opostos, aproximando-se:'),
(90, 1, 'Qual das correlações abaixo está totalmente correta?'),
(91, 1, 'Para que servem as cartas náuticas?'),
(92, 1, 'As coordenadas de um ponto, na carta náutica, são:'),
(93, 1, 'O que utilizamos, na carta náutica, para direcionar nosso rumo?'),
(94, 1, 'O que vem a ser rumo da embarcação e qual o instrumento de navegação mais usado para traçá-lo, na carta náutica?'),
(95, 1, 'As distâncias, na carta náutica, são medidas em que escala e em que unidade são expressas?'),
(96, 1, 'Os rumos nas cartas náuticas variam de 000? a 360? e são orientados a partir de um ponto de partida, até o ponto de chegada. Qual o instrumento de navegação que é utilizado para medir as distâncias entre estes pontos?'),
(97, 1, 'O posicionamento da carta náutica, para se fazer as plotagens de posição, rumos e outras marcações, deve ser:'),
(98, 1, 'Para que servem os Símbolos e Abreviaturas das cartas náuticas?'),
(99, 1, 'O navegador deverá utilizar cartas náuticas de que escala, para obter maiores detalhes e uma navegação segura, em trechos de águas interiores?'),
(100, 1, 'Quando observamos, na carta náutica, a escala 1:3000, isto quer dizer que:'),
(101, 1, 'As profundidades das cartas náuticas são:'),
(102, 1, 'Os paralelos são:'),
(103, 1, 'Os meridianos são:'),
(104, 1, 'Para se determinar a latitude de um ponto na carta náutica, devemos:'),
(105, 1, 'Para se determinar a longitude de um ponto na carta náutica, devemos:'),
(106, 1, 'A declinação magnética local é utilizada para:'),
(107, 1, 'Existe um valor que é encontrado no interior da rosa-dos-ventos e é multiplicado pelo total de anos de edição da carta náutica, até o ano atual, e este valor é somado ou subtraído da declinação magnética do local. Esse valor é:'),
(108, 1, 'Qual a publicação que explica e mostra o significado de todos os símbolos e abreviaturas contidos nas cartas náuticas?'),
(109, 1, 'Não consiste em uma medida de prevenção de incêndios:'),
(110, 1, 'Só haverá fogo quando:'),
(111, 1, 'A combustão é:'),
(112, 1, 'O que vem a ser o combustível?'),
(113, 1, 'O comburente é um elemento da natureza que reage com as substâncias para gerar a combustão e pode ser:'),
(114, 1, 'São equipamentos de combate a incêndio mais comumente encontrados a bordo das embarcações de esporte e recreio:'),
(115, 1, 'Extintores portáteis são:'),
(116, 1, 'Sua embarcação começa a pegar fogo e o vento está entrando por boreste. Qual o seu posicionamento para dar o combate às chamas?'),
(117, 1, 'Os agentes extintores são:'),
(118, 1, 'O extintor de água deve ser usado no combate a incêndios em:'),
(119, 1, 'O incêndio de classe A ocorre em:'),
(120, 1, 'O incêndio da classe B é o:'),
(121, 1, 'O incêndio da classe C é o:'),
(122, 1, 'Os extintores de CO2 são utilizados em:'),
(123, 1, 'Os extintores de espuma são utilizados em:'),
(124, 1, 'Para se usar o extintor de água deve-se:'),
(125, 1, 'Para se utilizar o extintor de CO2, deve-se:'),
(126, 1, 'Para se utilizar o extintor de espuma deve-se:'),
(127, 1, 'O combate a incêndio é muito auxiliado quando:'),
(128, 1, 'São cuidados que devemos ter com os extintores de CO2:'),
(129, 1, 'A água é um agente extintor que pode ser utilizado nos incêndios em:'),
(130, 1, 'Os extintores portáteis devem ser arrumados em:'),
(131, 1, 'Estou na cabine de comando e começo a sentir um cheiro de queimado vindo do motor. Qual o extintor portátil que deverei pegar?'),
(132, 1, 'Estou na popa da embarcação e vejo sair fumaça do console de navegação. Qual o extintor que devo pegar?'),
(133, 1, 'Podemos improvisar, para apagar incêndios, na falta de um extintor portátil:'),
(134, 1, 'Devo ter a bordo sempre extintores portáteis:'),
(135, 1, 'A quantidade e o tipo de extintor portátil, nas embarcações de esporte e recreio, devem ser cumpridos a bordo, para seguir viagem, e são definidos em:'),
(136, 1, 'Os sistemas fixos de combate à incêndios são:'),
(137, 1, 'Os incêndios, em locais de difícil acesso, são combatidos através de:'),
(138, 1, 'São agentes extintores:'),
(139, 1, 'Quando, por ocasião de um acidente a bordo, o acidentado não estiver respirando, devo proceder:'),
(140, 1, 'Para se realizar a respiração boca-a-boca, eu devo proceder antes, que verificação?'),
(141, 1, 'Qual a freqüência de sopros por minuto, numa respiração boca a boca?'),
(142, 1, 'Caso seja verificado que, após ter feito a respiração boca a boca, o coração da vítima ainda não está batendo, o procedimento correto será:'),
(143, 1, 'Caso o coração de uma vítima de um acidente a bordo, não esteja batendo, eu devo iniciar:'),
(144, 1, 'Qual é o outro sintoma que acompanha a parada cardíaca?'),
(145, 1, 'O que deve ser tentado no caso de parada cardíaca, e que às vezes funciona de imediato?'),
(146, 1, 'Após a massagem cardíaca ter feito o coração voltar a bater, o que deve ser feito é:'),
(147, 1, 'qual a freqüência ideal de compressão e descompressão do peito, na massagem cardíaca externa?'),
(148, 1, 'Quando houver, ao mesmo tempo, parada respiratória e parada cardíaca, como se deve proceder?'),
(149, 1, 'Na respiração boca a boca, eu sempre devo:'),
(150, 1, 'No caso de fratura de antebraço, podemos imobilizá-lo com:'),
(151, 1, 'O nome do dispositivo utilizado para imobilizar ossos quebrados por meio de tiras de pano amarradas a ele, é:'),
(152, 1, 'Para imobilizar o braço, eu devo deixá-lo:'),
(153, 1, 'Para fratura na perna, eu posso prender madeiras compridas, por meio de tiras de pano ou cintos, com a perna'),
(154, 1, 'A posição do pé, de uma perna quebrada, deve ser:'),
(155, 1, 'Caso exista risco de incêndio ou de explosão, em local próximo a vítima fraturada, eu deverei:'),
(156, 1, 'A vítima de choque elétrico precisa:'),
(157, 1, 'Qual dos materiais abaixo, eu não utilizaria, para afastar a vítima do contato com a corrente elétrica?'),
(158, 1, 'Após a retirada do contato com a corrente elétrica, caso seja necessário, o que deve ser feito?'),
(159, 1, 'As pequenas queimaduras ,devemos:'),
(160, 1, 'Antes de cobrir as queimaduras com pano limpo, devemos: '),
(161, 1, 'Nas grandes queimaduras, nunca se deve:'),
(162, 1, 'O que vem a ser a hemorragia'),
(163, 1, 'Para estancar uma hemorragia, devemos:'),
(164, 1, 'Para que é utilizado o torniquete?'),
(165, 1, 'Como aplicar o torniquete?'),
(166, 1, 'São cuidados importantes com o torniquete, exceto:'),
(167, 1, 'São atitudes certas, com relação a vítimas de grandes hemorragias:'),
(168, 1, 'Os primeiros socorros são :'),
(169, 1, 'Para que serve o colete salva-vidas, que deverá ser guardado a bordo, em quantidade exigida pela Portaria 0026/94, da DPC?'),
(170, 1, 'São equipamentos de salvatagem, exigidos em embarcação de esporte e recreio, exceto:'),
(171, 1, 'Qual dos equipamentos de salvatagem abaixo fica em um casulo fechado, e se infla com um dispositivo especial, para ser utilizado pelos náufragos?'),
(172, 1, 'O colete salva-vidas deve ser:'),
(173, 1, 'O número de coletes a bordo deve atender:'),
(174, 1, 'O colete salva-vidas deve ficar:'),
(175, 1, 'O que deve ser amarrado na bóia circular, para facilitar o resgate de alguém, que caiu na água?'),
(176, 1, 'A balsa rígida serve para ser utilizada:'),
(177, 1, 'O cabo, que prende a balsa rígida a embarcação, só deve ser cortado, quando:'),
(178, 1, 'Para embarcar na balsa, devemos evitar:'),
(179, 1, 'No caso de abandono de embarcação, por causa de incêndio incontrolável, devemos pular, quando houver óleo na superfície da água:'),
(180, 1, 'Devemos nadar, para nos afastar da embarcação acidentada, o mais rápido possível. Para isso devemos:'),
(181, 1, 'Caso não haja vazamentos de óleo e riscos de incêndio, nas proximidades da embarcação, devemos nos afastar dela:'),
(182, 1, 'São perigos à embarcação, em água interiores, exceto:'),
(183, 1, 'Nunca devemos:'),
(184, 1, 'Nunca devemos:'),
(185, 1, 'Para segurança da embarcação, devemos proceder a diversas verificações, antes de sairmos para navegar, exceto:'),
(186, 1, 'O excesso de peso, em partes altas da embarcação ou, má distribuição de pesos, em relação as laterais da embarcação, prejudica a:'),
(187, 1, 'A bóia circular deve ser presa:'),
(188, 1, 'A melhor maneira de saltar na água, utilizando o colete salva-vidas, é com:'),
(189, 1, 'Não se deve utilizar o colete salva-vidas, nas situações abaixo, exceto:'),
(190, 1, 'Para improvisar material flutuante, em o caso de naufrágio, devemos utilizar, exceto:'),
(191, 1, 'No caso de afogamento proceder do seguinte modo:'),
(192, 1, 'Caso o afogado não esteja respirando, qual o procedimento correto?'),
(193, 1, 'Caso o coração do afogado não esteja batendo, devo proceder:'),
(194, 1, 'São perigos ao náufrago nos rios, exceto:'),
(195, 1, 'As cobras podem ser identificadas como venenosas, ou não, através de:'),
(196, 1, 'A maior cobra que existe e, passa quase toda a vida na água, é:'),
(197, 1, 'As _____ ficam na lama, nas beiras dos rios e têm um ferrão venenoso, na ponta do rabo:'),
(198, 1, 'A pessoa deve procurar abandonar a embarcação:'),
(199, 1, 'O que significa a R-LESTA?'),
(200, 1, 'A navegação em mar aberto é aquela feita:'),
(201, 1, 'A navegação oceânica é obrigatoriamente:'),
(202, 1, 'O atendimento de embarcações em um dos portos brasileiros é:'),
(203, 1, 'Os aquaviários constituem os seguintes grupos:'),
(204, 1, 'A penalidade de suspensão do certificado de habilitação estabelecida para as infrações previstas no ''R-LESTA'', somente poderá ser aplicada:'),
(205, 1, 'A reincidência, para efeito de gradação das penalidades do ''R-LESTA'' é a repetição da mesma infração em um período igual ou inferior a:'),
(206, 1, 'São aplicáveis ao comandante, em caso de descumprimento das competências, uma multa e suspensão do Certificado de Habilitação até:'),
(207, 1, 'O que são as NORMAMs?'),
(208, 1, 'Não é permitido o tráfego e o fundeio de embarcação nas áreas consideradas de segurança. Assinale qual a alternativa não representa uma área de segurança:'),
(209, 1, 'Nenhuma embarcação pode:'),
(210, 1, 'As embarcações de esporte e recreio podem ser classificadas exceto como:'),
(211, 1, 'O Representante Regional da Autoridade Marítima é o:'),
(212, 1, 'A Bandeira Nacional deve ser, no interior dos portos, usada:'),
(213, 1, 'O cerimonial marítimo prevê o embandeiramento nas datas previstas. Assinale a alternativa falsa com relação ao embandeiramento:'),
(214, 1, 'Se você entregar a condução da embarcação, a alguém sem habilitação, acontecerá:'),
(215, 1, 'Constatada uma infração será lavrado o competente auto de infração. A defesa do infrator deverá ser feita no prazo de:'),
(216, 1, 'Nunca opere uma embarcação a motor a menos de:'),
(217, 1, 'É expressamente proibido sentar no(a) _____ de uma embarcação a motor.'),
(218, 1, 'Somente pessoas habilitadas como motonautas e maiores de _____ anos poderão pilotar ''JET-SKI''.'),
(219, 1, 'Os amadores condutores de dispositivos flutuantes, tipo canoas, caíques, caiaques, pedalinhos ou pranchas, utilizados para recreio ou prática de esportes, serão dispensados de:');

-- --------------------------------------------------------

--
-- Estrutura da tabela `prova`
--

DROP TABLE IF EXISTS `prova`;
CREATE TABLE IF NOT EXISTS `prova` (
	`id` int(11) NOT NULL AUTO_INCREMENT,
	`titulo` text NOT NULL,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Extraindo dados da tabela `prova`
--

INSERT INTO `prova` (`id`, `titulo`) VALUES
(1, 'Prova para obtenção de Arrais Amador');


-- --------------------------------------------------------

--
-- Estrutura da tabela `usuario`
--

DROP TABLE IF EXISTS `usuario`;
CREATE TABLE IF NOT EXISTS `usuario` (
	`id` INT(10) AUTO_INCREMENT NOT NULL,
	`nome` VARCHAR(100) NOT NULL,
	`email` VARCHAR(200) NOT NULL,
	`senha` VARCHAR(256) NOT NULL,
	`dt_insert` DATETIME NOT NULL,
	`dt_update` DATETIME NOT NULL,
	`prioridade` INT(1) NOT NULL,
	PRIMARY KEY(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Estrutura da tabela `mensagens`
--

DROP TABLE IF EXISTS `mensagens`;
CREATE TABLE IF NOT EXISTS `mensagens` (
	`id` INT(10) AUTO_INCREMENT NOT NULL,
	`nome` VARCHAR(100) NOT NULL,
	`email` VARCHAR(200) NOT NULL,
	`msg` TEXT NOT NULL,
	`ip` VARCHAR(15) NULL,
	`referer` VARCHAR(300) NULL,
	`dt_insert` DATETIME NOT NULL,
	PRIMARY KEY(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Constraints for dumped tables
--

--
-- Limitadores para a tabela `opcao`
--

ALTER TABLE `opcao`
ADD CONSTRAINT `pergunta_id` FOREIGN KEY (`pergunta_id`) REFERENCES `pergunta` (`id`);

--
-- Limitadores para a tabela `pergunta`
--

ALTER TABLE `pergunta`
ADD CONSTRAINT `prova_id` FOREIGN KEY (`prova_id`) REFERENCES `prova` (`id`);
